spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/test?useSSL=false&serverTimezone=UTC
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password:
    dbcp2:
      validation-query: SELECT 1
      test-while-idle: true

  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

jwt:
  header: api_key
  issuer: ndgndg91-good
  client-secret: 6eb80d65d8ea90ed2157a405fc93766309169bcbb4b771a800f83ba1d355f99e
  expiry-seconds: 900

logging:
  level:
    root: debug
