GET http://127.0.0.1:9090/member?offset=0&limit=10
api_key: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6WyJVU0VSIl0sImlzcyI6Im5kZ25kZzkxLWdvb2QiLCJuYW1lIjoibmRnbmRnOTEiLCJleHAiOjE1ODcyMDAzMDEsImlhdCI6MTU4NzE5OTQwMSwidXNlcktleSI6MzA1OTUsImVtYWlsIjoibmRnbmRnOTFAZ21haWwuY29tIn0.D6W5cQa_EKxVbpiFo4IGv3_ONRX56oWKnH1hEFhoEcJYQR3E-gbGD6gTmf171cKUrfUcUvzIooc2yyCQ0ktuEQ

###

POST http://127.0.0.1:9090/sign-in
Content-Type: application/json

{
"principal" : "ndgndg91@gmail.com",
"credentials": "123123"
}

###

POST http://127.0.0.1:9090/sign-up
Content-Type: application/json

{
"userName": "ndgndg91",
  "email": "ndgndg91@gmail.com",
  "password": "123123"
}

###
POST http://127.0.0.1:9090/sign-up
Content-Type: application/json

{
  "userName" : "donggil",
  "email": "donggil@sixshop.com",
  "password": "123123"
}

###

POST http://127.0.0.1:9090/sign-in
Content-Type: application/json

{
  "principal" : "donggil@sixshop.com",
  "credentials": "123123"
}

###