GET http://127.0.0.1:9090/member?offset=0&limit=10
api_key: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6WyJVU0VSIl0sImlzcyI6Im5kZ25kZzkxLWdvb2QiLCJuYW1lIjoibmRnbmRnOTEiLCJleHAiOjE1ODcyMDAzMDEsImlhdCI6MTU4NzE5OTQwMSwidXNlcktleSI6MzA1OTUsImVtYWlsIjoibmRnbmRnOTFAZ21haWwuY29tIn0.D6W5cQa_EKxVbpiFo4IGv3_ONRX56oWKnH1hEFhoEcJYQR3E-gbGD6gTmf171cKUrfUcUvzIooc2yyCQ0ktuEQ

###

POST http://127.0.0.1:8080/sign-in
Content-Type: application/json

{
"principal" : "ndgndg91@gmail.com",
"credentials": "$s0$e0801$QwLnCaWcQYwBoIAF4wJpzw==$CNcCO9dfrl12iQPczeZcFOedds+afWDQz1E2ige0Ass="
}

###

