GET http://127.0.0.1:8080/products/1?offset=0&limit=10
api_key: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6WyJVU0VSIl0sImlzcyI6Im5kZ25kZzkxLWdvb2QiLCJuYW1lIjoibmRnbmRnOTEiLCJleHAiOjE1ODc4ODM0MTEsImlhdCI6MTU4Nzg4MjUxMSwidXNlcktleSI6MzA1OTUsImVtYWlsIjoibmRnbmRnOTFAZ21haWwuY29tIn0.JKRxX7DzqBe3aeanp9jRVFjeum34QFq_FH2UFOhgOKDcpGY_5VYwuTfDD3LfEZPdCEJ1_AB-o2nxNhpo-hpLFw
###

POST http://127.0.0.1:9090/sign-in
Content-Type: application/json

{
  "principal" : "ndgndg91@gmail.com",
  "credentials": "$s0$e0801$QwLnCaWcQYwBoIAF4wJpzw==$CNcCO9dfrl12iQPczeZcFOedds+afWDQz1E2ige0Ass="
}

###